# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('startLat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('startLng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('finishLat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('finishLng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('segmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.DaySegment')),
            ],
        ),
        migrations.RenameModel(
            old_name='Adventures',
            new_name='Adventure',
        ),
        migrations.AddField(
            model_name='map',
            name='advId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Adventure'),
        ),
        migrations.AddField(
            model_name='daysegment',
            name='mapId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Map'),
        ),
    ]
