# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_daynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsegment',
            name='delay',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapsegment',
            name='distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
