# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_userprofilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='advStatus',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adventure',
            name='advType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
